steps:

  - name: gcr.io/kaniko-project/executor:latest
    args:
      - "--destination=eu.gcr.io/$PROJECT_ID/$_IMAGE_NAME"
      - "--cache=true"
      - "--cache-ttl=96h"
      - "--build-arg=TEST=isItWorking"

  - name: gcr.io/cloud-builders/gke-deploy:stable
    args:
      - "run"
      - "--filename=k8s-config"
      - "--location=${_CLUSTER_ZONE}"
      - "--cluster=${_CLUSTER_NAME}"
      - "--image=eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest"
