steps:
  - name: gcr.io/kaniko-project/executor:v0.19.0

    args:
      - "--destination=eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}"
      - "--cache=true"
      - "--cache-ttl=96h"
      - "--build-arg=REACT_APP_FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
      - "--build-arg=REACT_APP_API_URL=${_API_KEY}"

  - name: gcr.io/cloud-builders/gke-deploy:stable
    args:
      - "run"
      - "--filename=k8s-config"
      - "--location=${_CLUSTER_ZONE}"
      - "--cluster=${_CLUSTER_NAME}"
      - "--image=eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest"
