export enum TypeKey {
  // State

  RESET_APP_STATE_SUCCESS = 'RESET_APP_STATE_SUCCESS',
  RESET_APP_STATE_FAIL = 'RESET_APP_STATE_FAIL',

  // User

  SIGNUP_SUCCESS = 'SIGNUP_SUCCESS',
  SIGNUP_FAIL = 'SIGNUP_FAIL',

  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',

  GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAIL = 'GET_PROFILE_FAIL',

  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  LOGOUT_FAIL = 'LOGOUT_FAIL',

  SET_PROFILE_SUCCESS = 'SET_PROFILE_SUCCESS',
  SET_PROFILE_FAIL = 'SET_PROFILE_FAIL',

  // Template

  GET_PROJECT_TEMPLATES_SUCCESS = 'GET_PROJECT_TEMPLATES_SUCCESS',
  GET_PROJECT_TEMPLATES_FAIL = 'GET_PROJECT_TEMPLATES_FAIL',

  CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS',
  CREATE_TEMPLATE_FAIL = 'CREATE_TEMPLATE_FAIL',

  // Content

  GET_PROJECT_CONTENT_SUCCESS = 'GET_PROJECT_CONTENT_SUCCESS',
  GET_PROJECT_CONTENT_FAIL = 'GET_PROJECT_CONTENT_FAIL',

  CREATE_CONTENT_SUCCESS = 'CREATE_CONTENT_SUCCESS',
  CREATE_CONTENT_FAIL = 'CREATE_CONTENT_FAIL',

  // Project

  GET_OWN_PROJECTS_SUCCESS = 'GET_OWN_PROJECTS_SUCCESS',
  GET_OWN_PROJECTS_FAIL = 'GET_OWN_PROJECTS_FAIL',

  CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL',

  SELECT_PROJECT_SUCCESS = 'SELECT_PROJECT_SUCCESS',
  SELECT_PROJECT_FAIL = 'SELECT_PROJECT_FAIL',

  UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL',

  DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS',
  DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL',

  GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS',
  GET_MEMBERS_FAIL = 'GET_MEMBERS_FAIL',
}

export interface Test {
  type: TypeKey.RESET_APP_STATE_SUCCESS
  by: number
}
